all:
  children:
    redis_servers:
      hosts:
        redis-1:
          ansible_host: 100.64.0.22 # Tailscale IP
          ansible_user: root

    proxies:
      hosts:
        sg-router:
          ansible_host: 100.64.0.22 # public IP (used for SSH)
          ansible_user: root
          proxy_id: proxy-1
          proxy_tailscale_subnet: 10.1.0.0/16

        # proxy-2:
        #   ansible_host: 203.0.113.2
        #   ansible_user: root
        #   proxy_id: proxy-2
        #   proxy_tailscale_subnet: 10.2.0.0/16

    watchers:
      hosts:
        eu-pf:
          ansible_host: 100.64.0.18 # Tailscale IP (nodes are not public)
          ansible_user: root
          volumes_root: /var/lib/pterodactyl/volumes

        # node-gorilla-1:
        #   ansible_host: 100.x.x.21
        #   ansible_user: root
        #   volumes_root: /srv/pterodactyl/volumes   # GorillaServer uses different path
