---
- name: Reload sysctl
  command:
    argv:
      - sysctl
      - -p
      - /etc/sysctl.d/99-mcproxy.conf

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Reload nftables
  command:
    argv:
      - nft
      - -f
      - /etc/nftables.conf

- name: Restart tproxy routing
  systemd:
    name: mcproxy-tproxy-routing.service
    state: restarted

- name: Restart proxy
  command: docker compose --profile proxy up -d --build
  args:
    chdir: "{{ mcproxy_deploy_dir }}"
